name: 'Stale-Bot'
on:
  schedule:
    - cron: '30 1 * * *'

# see https://github.com/actions/stale

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          stale-issue-label: stale
          stale-pr-label: stale
          stale-issue-message: 'This issue is stale because it has 60 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          days-before-stale: 60
          days-before-close: 7
          close-issue-label: stale
          exempt-issue-labels: idea
          exempt-pr-labels: idea
